### ISSUE TITLE
Not installing the jinja2 templates?

### ISSUE THREAD

**Issue by Logan2211** [major/osa_differ#1]
Hey Major,

Trying osa-differ and it seems like it doesn't install the jinja2 templates

```
logan@officews ~ $ virtualenv venvs/osadiffer
New python executable in /Users/logan/venvs/osadiffer/bin/python
Installing setuptools, pip, wheel...done.
logan@officews ~ $ venvs/osadiffer/bin/pip install git+https://github.com/major/osa_differ
Collecting git+https://github.com/major/osa_differ
  Cloning https://github.com/major/osa_differ to /var/folders/rb/_g4q304d27n3s3dbf9pnymdc0000gn/T/pip-napYSJ-build
Collecting GitPython (from osa-differ==0.0.2)
Collecting jinja2 (from osa-differ==0.0.2)
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting PyYAML (from osa-differ==0.0.2)
Collecting requests (from osa-differ==0.0.2)
  Using cached requests-2.11.1-py2.py3-none-any.whl
Collecting gitdb>=0.6.4 (from GitPython->osa-differ==0.0.2)
Collecting MarkupSafe (from jinja2->osa-differ==0.0.2)
Collecting smmap>=0.8.5 (from gitdb>=0.6.4->GitPython->osa-differ==0.0.2)
Installing collected packages: smmap, gitdb, GitPython, MarkupSafe, jinja2, PyYAML, requests, osa-differ
  Running setup.py install for osa-differ ... done
Successfully installed GitPython-2.0.8 MarkupSafe-0.23 PyYAML-3.11 gitdb-0.6.4 jinja2-2.8 osa-differ-0.0.2 requests-2.11.1 smmap-0.9.0
logan@officews ~ $ venvs/osadiffer/bin/osa-differ 13.3.0 13.3.1 --gist
Traceback (most recent call last):
  File "venvs/osadiffer/bin/osa-differ", line 9, in <module>
    load_entry_point('osa-differ==0.0.2', 'console_scripts', 'osa-differ')()
  File "/Users/logan/venvs/osadiffer/lib/python2.7/site-packages/osa_differ/osa_differ.py", line 327, in run_osa_differ
    report = render_template('offline-header.j2', template_vars)
  File "/Users/logan/venvs/osadiffer/lib/python2.7/site-packages/osa_differ/osa_differ.py", line 219, in render_template
    rendered = jinja_env.get_template(template_file).render(template_vars)
  File "/Users/logan/venvs/osadiffer/lib/python2.7/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/logan/venvs/osadiffer/lib/python2.7/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/Users/logan/venvs/osadiffer/lib/python2.7/site-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: offline-header.j2
logan@officews ~ $ find venvs/osadiffer -iname *.j2
logan@officews ~ $
```

**Comment by major** [comment]
I think that was a bug in the earlier revisions. Are you still seeing that problem now?

**Comment by trumant** [comment]
@major I can confirm that the issue noted above persists with the master version
